// Coaching-note service: 2–3 specific sentences grounded in the call's own
// failed checks, generated by the active scoring model. Plain text, not JSON.
import { OLLAMA_URL, SCORING_MODEL } from "../ai/ollama";

export async function generateCoachingNote(
  agent: string,
  failures: Array<{ label: string; kind?: "must_do" | "must_not"; evidence?: string; timestamp?: string }>,
  strengths: string[],
): Promise<string> {
  const res = await fetch(`${OLLAMA_URL}/api/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: SCORING_MODEL,
      stream: false,
      options: { temperature: 0.3 },
      messages: [
        {
          role: "system",
          content:
            "You are a call-center QA coach. Write a coaching note of 2 to 3 sentences for the agent. " +
            "Name one strength, name the single most important fix with its timestamp, keep it kind and specific. " +
            "Plain text only, no JSON, no greeting.",
        },
        {
          role: "user",
          content:
            `Write the coaching note for ${agent === "Uploaded call" ? "this agent" : agent} now.\n\n` +
            `What went well:\n${strengths.length ? strengths.map((s) => `- ${s}`).join("\n") : "- nothing recorded"}\n\n` +
            `What went wrong:\n${
              failures.length
                ? failures
                    .map(
                      (f) =>
                        // Spell out which way the rule was missed: a "Never…" label alone gets read backwards.
                        `- ${f.kind === "must_not" ? `Broke the rule "${f.label}" by doing exactly that` : `Skipped a required step: ${f.label}`}` +
                        `${f.timestamp ? ` (at ${f.timestamp})` : ""}${f.evidence ? `. The agent said "${f.evidence}"` : ""}`,
                    )
                    .join("\n")
                : "- nothing; every check passed"
            }\n\n` +
            "Reply with the note only: 2 to 3 sentences addressed to the agent as 'you'. Do not repeat these lists. " +
            "Never tell the agent to do something a rule forbids.",
        },
      ],
    }),
  });
  if (!res.ok) throw new Error(`coaching request failed: ${res.status}`);
  const data = (await res.json()) as { message?: { content?: string } };
  return (data.message?.content ?? "").trim();
}
