// Coaching-note service: 2–3 specific sentences grounded in the call's own
// failed checks, generated by the active scoring model. Plain text, not JSON.
import { OLLAMA_URL, SCORING_MODEL } from "../ai/ollama";

export async function generateCoachingNote(
  agent: string,
  failures: Array<{ label: string; evidence?: string; timestamp?: string }>,
  strengths: string[],
): Promise<string> {
  const res = await fetch(`${OLLAMA_URL}/api/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: SCORING_MODEL,
      stream: false,
      options: { temperature: 0.3 },
      messages: [
        {
          role: "system",
          content:
            "You are a call-center QA coach. Write a coaching note of 2 to 3 sentences for the agent. " +
            "Name one strength, name the single most important fix with its timestamp, keep it kind and specific. " +
            "Plain text only, no JSON, no greeting.",
        },
        {
          role: "user",
          content:
            `Agent: ${agent}\n` +
            `Strengths: ${strengths.length ? strengths.join("; ") : "none recorded"}\n` +
            `Misses: ${failures.map((f) => `${f.label} (${f.timestamp ?? "no timestamp"}): ${f.evidence ?? "no quote"}`).join("; ")}`,
        },
      ],
    }),
  });
  if (!res.ok) throw new Error(`coaching request failed: ${res.status}`);
  const data = (await res.json()) as { message?: { content?: string } };
  return (data.message?.content ?? "").trim();
}
